server:
   # 0 表示随机端口
   port: 0
   
spring:
   application:
      name: xk-user
   datasource:
      driverClassName: com.mysql.jdbc.Driver
      #&serverTimezone=GMT%2B8
      url: jdbc:mysql://127.0.0.1/C89-S2-xk?useSSL=false
      username: root
      password: a
   mail:
      # 邮箱服务器地址
      host: smtp.qq.com
      # 用户名
      username: 2963465238@qq.com
      # 密码 
      password: rfjytyizqlmpdcie
      default-encoding: UTF-8

eureka:
   client:
      serviceUrl:
         defaultZone: http://127.0.0.1:8000/eureka
         
# 设定 feign.hystrix.enabled=true，那么Feign将用断路器包装所有的控制层方法
feign:
  hystrix:
    enabled: true
    
logging:
   level:
      com.yc.blog: debug
      
# 以谁来发送邮件（自定义的配置信息）
mail:
   from:
      addr: 2963465238@qq.com